name: Build with Gradle and Automatic Versioning

on:
  pull_request:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Release

    runs-on: ubuntu-latest
    permissions:  # Add permissions here
      contents: write

    steps:
      # ... (Rest of your steps: Checkout, Setup JDK, Build, Extract Version) 

      - name: Create Release
        id: create_release
        uses: actions/github-script@v6
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          script: |
            const releaseType = "${{ steps.extract_version.outputs.RELEASE_TYPE }}"; 
            const releaseVersion = "${{ steps.extract_version.outputs.RELEASE_VERSION || 'v1.0.1' }}";
            const releaseName = `${releaseType} Update ${releaseVersion}`;
            const releaseBody = `${{ github.event.head_commit.message }}`; 

            try {
              console.log(`Creating release for tag ${releaseVersion}`);
              await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: releaseVersion,
                name: releaseName,
                body: releaseBody,
                draft: false,
                prerelease: false,
              });
            } catch (error) {
              console.error("Error creating release:", error); 
            }